name: premsql
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.18
  - pip=25.2
  - python=3.10.18
  - setuptools=80.9.0
  - sqlite=3.50.2
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - asgiref==3.10.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - black==24.10.0
      - blinker==1.9.0
      - cachetools==6.2.1
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - datasets==2.21.0
      - dill==0.3.8
      - distro==1.9.0
      - django==5.2.7
      - djangorestframework==3.16.1
      - drf-yasg==1.21.11
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - fastapi==0.112.4
      - filelock==3.20.0
      - filetype==1.2.0
      - flask==3.1.2
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2024.6.1
      - func-timeout==4.3.5
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-ai-generativelanguage==0.9.0
      - google-api-core==2.27.0
      - google-auth==2.41.1
      - googleapis-common-protos==1.71.0
      - greenlet==3.2.4
      - grpcio==1.76.0
      - grpcio-status==1.76.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.26.0
      - httpx-sse==0.4.3
      - huggingface-hub==0.24.7
      - idna==3.11
      - inflection==0.5.1
      - isort==5.13.2
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jiter==0.11.1
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kagglehub==0.3.13
      - kiwisolver==1.4.9
      - langchain==1.0.1
      - langchain-community==0.3.31
      - langchain-core==1.0.0
      - langchain-google-genai==3.0.0
      - langgraph==1.0.1
      - langgraph-checkpoint==3.0.0
      - langgraph-prebuilt==1.0.1
      - langgraph-sdk==0.2.9
      - langsmith==0.4.37
      - markupsafe==3.0.3
      - marshmallow==3.26.1
      - matplotlib==3.10.7
      - multidict==6.7.0
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - mysql-connector-python==9.4.0
      - narwhals==2.9.0
      - numpy==1.26.4
      - openai==1.109.1
      - orjson==3.11.3
      - ormsgpack==1.11.0
      - packaging==25.0
      - pandas==2.3.3
      - pathspec==0.12.1
      - pillow==10.4.0
      - platformdirs==4.5.0
      - premai==0.3.107
      - premsql==0.2.10
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==6.33.0
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pydantic-settings==2.11.0
      - pydeck==0.9.1
      - pymysql==1.1.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rpds-py==0.27.1
      - rsa==4.9.1
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sqlalchemy==2.0.44
      - sqlparse==0.5.3
      - starlette==0.38.6
      - streamlit==1.50.0
      - tenacity==9.1.2
      - toml==0.10.2
      - tomli==2.3.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uritemplate==4.2.0
      - urllib3==2.5.0
      - uvicorn==0.32.1
      - watchdog==6.0.0
      - werkzeug==3.1.3
      - xxhash==3.6.0
      - yarl==1.22.0
      - zstandard==0.25.0
prefix: E:\conda_envs\premsql
